# Generated by Django 5.1 on 2024-08-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_remove_messages_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='last_name',
            new_name='lastNname',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='subject_matter',
            new_name='subjectMatter',
        ),
    ]
